In [2]:
import numpy as np

Exercicio 1

In [2]:
exerc1 = np.random.randint(0,100,size=(10))
exerc1

array([68, 45, 52, 26, 95, 37, 21, 30, 81, 49], dtype=int32)

Exercicio 2


In [4]:
exerc2 = np.random.rand(5,5)
print("min : ",exerc2.min())
print("max : ",exerc2.max())
print("media : ",exerc2.mean())

min :  0.030443365790927435
max :  0.9558396176063074
media :  0.5306466480754846


Exercicios 3


In [8]:
exerc3 = np.random.rand(10)
exerc3_int = (exerc3 * 10).astype(int)
print(exerc3)
print(exerc3_int)

[0.96826598 0.45124075 0.29150407 0.87472863 0.4815413  0.00987415
 0.10856044 0.24961201 0.43904348 0.68771676]
[9 4 2 8 4 0 1 2 4 6]


Exercicio 4


In [13]:
rod = np.random.randint(0,9,size=(3,3))
rod[1, :] = -1
rod

array([[ 4,  0,  5],
       [-1, -1, -1],
       [ 4,  2,  5]], dtype=int32)

In [ ]:
Exercicio 5

In [18]:
import pandas as pd

exerc5 = np.array([["Banana",7.90,12],["Maça",10.20,3],["Pera",11.80,4]])
exerc51 = pd.DataFrame(exerc5,columns=["FRUTA","PREÇO","QUANTIDADE"])
exerc51



FRUTA PREÇO QUANTIDADE
0  Banana   7.9         12
1    Maça  10.2          3
2    Pera  11.8          4

In [19]:
data = {"fruta": ["Banana", "Maça", "Pera"],
        "preco": [7.90, 10.20, 11.80],
        "quantidade": [12, 3, 4]}

df = pd.DataFrame(data)
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4